name: pillpal
description: A medication reminder app built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  android_alarm_manager_plus: ^4.0.7
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

dependency_overrides:
  analyzer: ^6.11.0
  source_gen: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/alarm.mp3

